name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/FirLib.sln
      
    - name: Build
      run: dotnet build -c Release ./src/FirLib.sln --no-restore
      
    - name: Test
      run: dotnet test -c Release ./src/FirLib.sln --no-build --verbosity normal
  
    - name: Pack
      run: dotnet pack -c Release -o ./publish ./src/FirLib.sln /p:ContinuousIntegrationBuild=true
