name: Build and test (.Net 7.0.x on Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore src/MessageCommunicator.sln
    - name: Build
      run: dotnet build src/MessageCommunicator.sln --configuration Release-CI --no-restore --no-incremental --framework net7.0
    - name: Test
      run: dotnet test src/MessageCommunicator.sln --configuration Release-CI --no-restore --framework net7.0 --verbosity normal
